services:
  ganache:
    build:
      context: ./RewardingSystem
      target: ganache
    ports:
      - 8545:8545
    networks:
      - backend
    volumes:
      - ganache_data:/home

  truffle:
    build:
      context: ./RewardingSystem
      target: truffle
    depends_on:
      - ganache
    networks:
      - backend
    volumes:
      - ./RewardingSystem:/home/app
      - /home/app/node_modules

      

  api_gateway:
      build: .
      ports:
        - 8080:8080
      networks:
        - backend
  
networks:
  backend:
    driver: "bridge"

volumes:
  ganache_data: {}



# 1. Start the Blockchain Etherum Server (Ganache)
# 2. Get the Accounts and Private Keys
# 3. Update the Truffle Holder (Base Account) to Give it the Needed ATN
# 4. Deploy the Contract with Truffle to the Ganache Network with command:
# > truffle migrate --network development
# 5. Change the constants in assistantion_config.py
# base_account_private_key = (
#     "0xe60dcb5f348bc73c75dfca0acc24ab06a70de5c07a519c6fb84e48b8aa6dd0a4"
# )
# base_account_address = "0x927cca6E5Cd04176f792DEa87C06B08E64aBf5Ec"

# contract_address = "0xCa0Da2766B7BfC0e0EA221448174a4e11Fdf79B0"